version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: xlex_base_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mr1703

  web:
    build: .
    command: gunicorn xlexapp.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
    - ALLOWED_HOSTS=34.122.81.106,xlex.com.br,www.xlex.com.br


volumes:
  postgres_data:

